### ISSUE TITLE
Arabic support 

### ISSUE THREAD

**Issue by mzeidhassan** [ModernMT/DataCollection#13]
Hello everybody,

Do you plan to support Arabic in this project? I looked at the dicts folder and I didn't see "en-ar" dict. 
If you plan to support Arabic, I can help with the en-ar dictionary if you don't have one already.

Thanks!
Mohamed

**Comment by achimr** [comment]
Hello Mohamed, thanks for your interest in the DataCollection! Right now we have no immediate plans to support Arabic. But I just put up [instructions how to build dictionaries](/baseline/dictionary.md) (this is in the dev branch for now). The only other thing I believe you need is a nonbreaking_prefix file for Arabic (you can see examples for many languages in `~/moses/scripts/share/nonbreaking_prefixes`.

Because we haven't tested the pipeline for Arabic you might run into issues. Please report them here in the issue tracker. And of course we would be glad if you could contribute any dictionary that includes Arabic. Thanks in advance!

Please add a comment whether this resolved your question or not.

**Comment by mzeidhassan** [comment]
Thanks you so much Achim for your reply and the instructions. I will follow them and I will keep you posted. 

Yes, this answers my question for now. You can close the issue.

Thanks,
Mohamed
